set(_CATKIN_CURRENT_PACKAGE "sc_localization")
set(sc_localization_VERSION "0.0.0")
set(sc_localization_MAINTAINER "dji <jq.zhang@dji.com>")
set(sc_localization_PACKAGE_FORMAT "2")
set(sc_localization_BUILD_DEPENDS )
set(sc_localization_BUILD_EXPORT_DEPENDS )
set(sc_localization_BUILDTOOL_DEPENDS "catkin")
set(sc_localization_BUILDTOOL_EXPORT_DEPENDS )
set(sc_localization_EXEC_DEPENDS )
set(sc_localization_RUN_DEPENDS )
set(sc_localization_TEST_DEPENDS )
set(sc_localization_DOC_DEPENDS )
set(sc_localization_URL_WEBSITE "")
set(sc_localization_URL_BUGTRACKER "")
set(sc_localization_URL_REPOSITORY "")
set(sc_localization_DEPRECATED "")