// Generated by gencpp from file simple_msgs/CastleEnergy.msg
// DO NOT EDIT!


#ifndef SIMPLE_MSGS_MESSAGE_CASTLEENERGY_H
#define SIMPLE_MSGS_MESSAGE_CASTLEENERGY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_msgs
{
template <class ContainerAllocator>
struct CastleEnergy_
{
  typedef CastleEnergy_<ContainerAllocator> Type;

  CastleEnergy_()
    : red_energy(0)
    , blue_energy(0)  {
    }
  CastleEnergy_(const ContainerAllocator& _alloc)
    : red_energy(0)
    , blue_energy(0)  {
  (void)_alloc;
    }



   typedef uint8_t _red_energy_type;
  _red_energy_type red_energy;

   typedef uint8_t _blue_energy_type;
  _blue_energy_type blue_energy;





  typedef boost::shared_ptr< ::simple_msgs::CastleEnergy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_msgs::CastleEnergy_<ContainerAllocator> const> ConstPtr;

}; // struct CastleEnergy_

typedef ::simple_msgs::CastleEnergy_<std::allocator<void> > CastleEnergy;

typedef boost::shared_ptr< ::simple_msgs::CastleEnergy > CastleEnergyPtr;
typedef boost::shared_ptr< ::simple_msgs::CastleEnergy const> CastleEnergyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_msgs::CastleEnergy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_msgs::CastleEnergy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'simple_msgs': ['/home/robomaster/robomaster/sc_code/src/simple_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_msgs::CastleEnergy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_msgs::CastleEnergy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_msgs::CastleEnergy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9299551f2d90f96de59e7c55bb10e426";
  }

  static const char* value(const ::simple_msgs::CastleEnergy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9299551f2d90f96dULL;
  static const uint64_t static_value2 = 0xe59e7c55bb10e426ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_msgs/CastleEnergy";
  }

  static const char* value(const ::simple_msgs::CastleEnergy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 red_energy\n\
uint8 blue_energy\n\
";
  }

  static const char* value(const ::simple_msgs::CastleEnergy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red_energy);
      stream.next(m.blue_energy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CastleEnergy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_msgs::CastleEnergy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_msgs::CastleEnergy_<ContainerAllocator>& v)
  {
    s << indent << "red_energy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red_energy);
    s << indent << "blue_energy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue_energy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_MSGS_MESSAGE_CASTLEENERGY_H
